DROP TABLE Notice;

CREATE TABLE Notice
(
    ID        NUMBER(10, 0) NOT NULL,
    TITLE     VARCHAR(200)  NOT NULL,
    CONTENT   VARCHAR(2000) NOT NULL,
    AUTHOR    VARCHAR(200)  NOT NULL,
    CREATED_AT DATE          NOT NULL,
    UPDATED_AT DATE          NOT NULL,
    VIEW_COUNT NUMBER(20, 0) NOT NULL,
    PRIMARY KEY (ID)
);

DROP SEQUENCE NOTICEID_SEQ;

CREATE SEQUENCE NOTICEID_SEQ
    MAXVALUE 9999999
    CACHE 2;

COMMIT;