DROP TABLE Member;

CREATE TABLE Member
(
    ID         NUMBER(10, 0) NOT NULL,
    USERNAME   VARCHAR(20)   NOT NULL,
    PASSWORD   VARCHAR(20)   NOT NULL,
    EMAIL      VARCHAR(30)   NOT NULL,
    CREATED_AT DATE          NOT NULL,
    PRIMARY KEY (ID)
);

DROP SEQUENCE MEMBERID_SEQ;

CREATE SEQUENCE MEMBERID_SEQ
    MAXVALUE 9999999
    CACHE 2;

DELETE
FROM Member;

COMMIT;