DROP TABLE Music;

CREATE TABLE Music
(
    ID         NUMBER(10, 0) NOT NULL,
    TITLE      VARCHAR(200)  NOT NULL,
    CONTENT    VARCHAR(2000) NOT NULL,
    AUTHOR     VARCHAR(200)  NOT NULL,
    RELEASED_AT DATE          NOT NULL,
    CREATED_AT  DATE          NOT NULL,
    PRIMARY KEY (ID)
);

DROP SEQUENCE MUSICID_SEQ;

CREATE SEQUENCE MUSICID_SEQ
    MAXVALUE 9999999 -- 기본값 10의 28승 => 생략안됨
    CACHE 2; -- 기본값 20 => 생략안됨

DELETE FROM Music;

COMMIT;